import {
    Button
} from "@mui/material";


function DownloadReport({

    parameters,

    selectedSymptoms,

    prediction

}){


const generateReport=()=>{


const report = `

🧪 AI Urine Disease Predictor Report

-----------------------------------

Urine Parameters:

${parameters.join(", ")}


Selected Symptoms:

${selectedSymptoms.join(", ")}


Predicted Diseases:

${prediction.disease.join("\n")}


Related Symptoms:

${prediction.symptoms.join("\n")}


Doctor Consultation:

${
prediction.needs_consultation_suggestion
?
"Recommended"
:
"Not Required"
}


Reason:

${
prediction.reason_for_suggestion || 
"No additional advice"
}


-----------------------------------

Generated by AI system.

`;



const blob = new Blob(
    [report],
    {
        type:"text/plain"
    }
);



const url =
URL.createObjectURL(blob);



const link =
document.createElement("a");



link.href=url;


link.download=
"urine_prediction_report.txt";


link.click();



URL.revokeObjectURL(url);



};



return (

<Button

variant="outlined"

color="primary"

fullWidth

sx={{
marginTop:2
}}

onClick={generateReport}

>

📄 Download Report

</Button>

);


}


export default DownloadReport;